name: Build, Push, and Deploy Docker Image to Google Cloud Platform
    
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - '**/*.draft.md'

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: drawdigitreco
      PROJECT_ID: maximal-shadow-446510-n3
      REGION: asia-south1 # Change to your Cloud Run region
      SERVICE_NAME: digitreco # Change to your Cloud Run service name
      PORT : 8501
      MEMORY : 4Gi

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker Client for GCR
      run: gcloud auth configure-docker --quiet

    - name: Write GCP credentials to JSON file
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > credentials.json

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    

    - name: Push Docker Image to Google Container Registry (GCR)
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
          --platform managed \
          --region $REGION \
          --port "${{ env.PORT }}" \
          --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS" = "${{ secrets.GCP_SA_KEY }}" \
          --memory "${{ env.MEMORY }}"

    - name: Set IAM Policy to Allow Public Access
      run: |
        gcloud run services add-iam-policy-binding $SERVICE_NAME \
          --region=$REGION \
          --member="allUsers" \
          --role="roles/run.invoker"

          
